name = "the-urbann-api"
compatibility_date = "2024-01-01"
main = "functions/api/[[path]].ts"

[[r2_buckets]]
binding = "IMAGES_BUCKET"
bucket_name = "theurbann-gallery"

[[d1_databases]]
binding = "DB"
database_name = "urbann_db"
database_id = "53065fd4-b4ba-41b1-9b2b-0149dd08155f"

[vars]
ENVIRONMENT = "production"
JWT_SECRET = "urbann-secret-2024"
R2_PUBLIC_URL = "https://pub-bb51c92ec25541b7bac2969eeb40169b.r2.dev"